### ISSUE TITLE
Exeption in plagin RoboPOGOGenerator 2.2.0

### ISSUE THREAD

**Issue by KyleQA** [robohorse/RoboPOJOGenerator#99]
Hi! I have a problem with import data. Could you help me?

**Additional Information:**
IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 25, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
Non-Bundled Plugins: Lombook Plugin, com.robohorse.robopojogenerator, mobi.hsz.idea.gitignore, org.jetbrains.kotlin

**java version "1.8.0_261"**

**Text error:**
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.json.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; org.json.JSONObject is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5e02af71)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor$2.onJsonObjectIdentified(ClassProcessor.java:97)
	at com.robohorse.robopojogenerator.generator.processing.InnerObjectResolver.resolveClassType(InnerObjectResolver.kt:12)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.proceedArray(ClassProcessor.java:112)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.access$000(ClassProcessor.java:20)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor$1.onJsonArrayIdentified(ClassProcessor.java:60)
	at com.robohorse.robopojogenerator.generator.processing.InnerObjectResolver.resolveClassType(InnerObjectResolver.kt:13)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.proceed(ClassProcessor.java:65)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor$2.onJsonObjectIdentified(ClassProcessor.java:99)
	at com.robohorse.robopojogenerator.generator.processing.InnerObjectResolver.resolveClassType(InnerObjectResolver.kt:12)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.proceedArray(ClassProcessor.java:112)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.access$000(ClassProcessor.java:20)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor$1.onJsonArrayIdentified(ClassProcessor.java:60)
	at com.robohorse.robopojogenerator.generator.processing.InnerObjectResolver.resolveClassType(InnerObjectResolver.kt:13)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.proceed(ClassProcessor.java:65)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor$1.onJsonObjectIdentified(ClassProcessor.java:45)
	at com.robohorse.robopojogenerator.generator.processing.InnerObjectResolver.resolveClassType(InnerObjectResolver.kt:12)
	at com.robohorse.robopojogenerator.generator.processing.ClassProcessor.proceed(ClassProcessor.java:65)
	at com.robohorse.robopojogenerator.generator.RoboPOJOGenerator.generate(RoboPOJOGenerator.kt:16)
	at com.robohorse.robopojogenerator.generator.consts.common.ClassCreator.generateFiles(ClassCreator.kt:17)
	at com.robohorse.robopojogenerator.delegates.GenerationDelegate$runGenerationTask$1.run(GenerationDelegate.kt:25)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by VadimSchenev** [comment]
Hi! Could you please share how it was happened? Did you try to generate POJO from JSON? Could you please share that json if it is possible?

**Comment by KyleQA** [comment]
I've found reason - problem with response. Thanks!
